version: 0.2    
phases:
  install:
    commands:
      - npm install
      - npm install -g serverless
      - npm install serverless-offline
      - npm install serverless-plugin-existing-s3
  build:
    commands:
      - cd dataio
      - sls deploy
      - sls s3deploy