const QUERY_TYPES = {
  // WorkOrders
  RESET_ALL_BLACKOUT_FLAGS_BY_PROJECT_ID: 'RESET_ALL_BLACKOUT_FLAGS_BY_PROJECT_ID',
  SET_BLACKOUT_FLAGS_BY_PROJECT_ID_AND_DATE: 'SET_BLACKOUT_FLAGS_BY_PROJECT_ID_AND_DATE',

  // Reports
  GET_EXCEPTION_REPORT_DATA: 'GET_EXCEPTION_REPORT_DATA',
  GET_CONDITION_REPORT_DATA: 'GET_CONDITION_REPORT_DATA',
  GET_METER_DEPLOY_ASSIGNMENTS_REPORT_DATA: 'GET_METER_DEPLOY_ASSIGNMENTS_REPORT_DATA',
  GET_WATER_METER_DEPLOY_ASSIGNMENTS_REPORT_DATA: 'GET_WATER_METER_DEPLOY_ASSIGNMENTS_REPORT_DATA'
}

module.exports = {
  QUERY_TYPES
}